apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # 'prometheus' must match the service name in docker compose
    url: http://prometheus:9090 
    isDefault: true
    editable: false # 'false' prevents accidental UI changes

