apiVersion: 2

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_ds
    url: http://lgtm:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo_ds
    
  - name: Tempo
    type: tempo
    uid: tempo_ds
    url: http://lgtm:3200
    access: proxy
    editable: false
    jsonData:
      httpMethod: GET