global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blogengine'
    static_configs:
      - targets: ['blogengine:3000']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
  